changed base image to use node:buster

diff --git a/docker/node/Dockerfile b/docker/node/Dockerfile
--- a/docker/node/Dockerfile
+++ b/docker/node/Dockerfile
@@ -1,23 +1,43 @@
-FROM docker:latest
+FROM node:14-buster
 
-ENV NodeVersion=12.15.0-r1
+ENV DOCKER_VERSION=20.10.1
+ENV AWS_CLI=2.0.30
 
-RUN apk update && apk upgrade \
-    && apk add --no-cache \
-            nodejs=${NodeVersion} \
-            npm \
-            python3 \
-            python3-dev \
-            gcc \
-            musl-dev \
-            jq \
-            make \
-    && pip3 --disable-pip-version-check install \
-            awscli \
-            aws-sam-cli \
-    && apk -v --purge --no-cache del \
-            gcc \
-            python3-dev \
-            musl-dev
+RUN apt-get update && apt install -y \
+       jq \
+       make \
+       ca-certificates \
+       openssh-client \
+    && mkdir -p /tmp/build-deps \
+    && cd /tmp/build-deps/ \
+    && set -eux; \
+       	apkArch="$(dpkg --print-architecture)"; \
+       	case "$apkArch" in \
+       		'x86_64' | 'amd64') \
+       			dockerArch='x86_64'; \
+       			;; \
+       		'armhf') \
+       			dockerArch='armel'; \
+       			;; \
+       		'armv7') \
+       			dockerArch='armhf'; \
+       			;; \
+       		'aarch64') \
+       			dockerArch='aarch64'; \
+       			;; \
+       		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;; \
+       	esac \
+    && curl "https://download.docker.com/linux/static/stable/$dockerArch/docker-${DOCKER_VERSION}.tgz" -o "docker.tgz" \
+    && tar --extract \
+        --file docker.tgz \
+        --strip-components 1 \
+        --directory /usr/local/bin/ \
+    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI}.zip" -o "awscliv2.zip" \
+    && unzip -q awscliv2.zip \
+    && ./aws/install \
+    && curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" \
+       -o "session-manager-plugin.deb" \
+    && dpkg -i session-manager-plugin.deb \
+    && rm -r /tmp/build-deps/
 
 RUN npm i -g aws-cdk
